name: first_workflow
on:
  push:
    branches:
      - main
jobs:
  example-jop:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to our frist github action workflow!"

      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Repository file
        run: ls -la
